export const yellow = "#ffefba";
export const main = "#222831";
export const earth = "#FDC830";
export const gradient = "linear-gradient(to right, #ffefba, #ffffff)";
export const green = "#00887A";
export const blue = "#77a6f7";
export const lightBlue = "#d3e3fc";
export const bg = "#c5cbe3";
export const honey = "#DCAE1d";
